sudo: required
language: shell
services:
- docker
before_install:
- docker build -t "aaronbbrown/http-bench-target:$TRAVIS_BRANCH" .
after_success:
- docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" && docker push aaronbbrown/http-bench-target
